//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackofficeDesktop.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BackofficeDesktop.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;Canvas xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; Name=&quot;svg2&quot; Width=&quot;544&quot; Height=&quot;602&quot;&gt;&lt;Canvas.Resources/&gt;&lt;Canvas Name=&quot;layer1&quot;&gt;&lt;Path xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot; Name=&quot;path2987&quot; Stroke=&quot;#FF000000&quot; StrokeThickness=&quot;1&quot; StrokeLineJoin=&quot;Miter&quot; StrokeStartLineCap=&quot;Flat&quot; StrokeEndLineCap=&quot;Flat&quot; Data=&quot;m 510 490.93361 -5.71428 -162.85714 -42.85715 48.57142 -42.85714 -37.14285 2.85714 74.28571 -185.71428 11.42857 188.57143 5.71 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PinHorizontal {
            get {
                return ResourceManager.GetString("PinHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;Canvas xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; Name=&quot;svg2&quot; Width=&quot;744&quot; Height=&quot;1052&quot;&gt;&lt;Canvas.Resources/&gt;&lt;Canvas Name=&quot;layer1&quot;&gt;&lt;Path xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot; Name=&quot;path2987&quot; Stroke=&quot;#FF000000&quot; StrokeThickness=&quot;1&quot; StrokeLineJoin=&quot;Miter&quot; StrokeStartLineCap=&quot;Flat&quot; StrokeEndLineCap=&quot;Flat&quot; Data=&quot;m 448.57143 278.07647 -162.85714 5.71428 48.57142 42.85715 -37.14285 42.85714 74.28571 -2.85714 11.42857 185.71428 5.71429 -1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PinVertical {
            get {
                return ResourceManager.GetString("PinVertical", resourceCulture);
            }
        }
    }
}
